version: '3.9'

networks:
  bh_network:
    name: BH_Network
    driver: bridge

services:
  web:
    build: 
      context: .
      dockerfile: BH.Case.API/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - OPENAPI_SERVER_URL=http://localhost:8080
    networks:
      - bh_network

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: BH-swagger-ui
    ports:
      - "8081:8080"
    environment:
      - API_URL=http://localhost:8080/openapi/v1.json
    depends_on:
      - web 
    networks:
      - bh_network