version: '3.9'

networks:
  BlueHarvest_Network:
    name: BlueHarvest_Network
    driver: bridge

services:
  web:
    build: 
      context: .
      dockerfile: BlueHarvest_Case.API/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - OPENAPI_SERVER_URL=http://localhost:8080
    networks:
      - BlueHarvest_Network

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: blueharvest-swagger-ui
    ports:
      - "8081:8080"
    environment:
      - API_URL=http://localhost:8080/openapi/v1.json
    depends_on:
      - web 
    networks:
      - BlueHarvest_Network

  frontend:
    build:
      context: ./blueharvest_case.frontend
      dockerfile: Dockerfile
    container_name: blueharvest-frontend
    ports:
      - "3000:3000"
    depends_on:
      - web
    networks:
      - BlueHarvest_Network
